# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Latest Blog
  description: List of Latest Blog items
  icon: fiber_new
  tags:
    - Data

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  show_post_tags: true
  show_post_date: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: ""

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
