# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Number Counter
  description: Animated Number Counter from Zero
  icon: plus_one
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  caption_alignment: left
  caption_title: ""
  main_title: ""
  description_html: ""
  columns_to_display: "2"
  items:
    - counter_alignment: Left
      counter_number: 0
      counter_symbol: ""
      title: ""
      description_html: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  caption_title: This is a caption title
  main_title: This is a main title
  description_html: This is a description
  items:
    - counter_symbol: ""
      title: This is a title
      description_html: This is a description

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  alignment:
    type: select
    options:
      values:
        - Left
        - Center
        - Right
  columns_to_display:
    type: select
    options:
      values:
        - "2"
        - "3"
        - "4"
