paths:
  uploads: static/images
collections_config:
  pages:
    path: content
    output: true
    icon: feed
    _enabled_editors:
      - visual
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      page:
        path: schemas/page.html
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  articles:
    path: content/blog
    output: true
    icon: article
    _enabled_editors:
      - content
      - visual
    add_options:
      - name: Add Article
        editor: content
        schema: post
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      post:
        path: schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  data:
    path: data
    output: true
    filter:
      exclude:
        - footer.yaml
        - nav.yaml
    icon: settings
    _enabled_editors:
      - data
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
  site_navigation:
    path: data
    output: true
    filter:
      base: none
      include:
        - nav.yaml
        - footer.yaml
    icon: table_rows
    _enabled_editors:
      - data
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Blogging
    collections:
      - articles
  - heading: Site Settings
    collections:
      - data
      - site_navigation
_inputs:
  content:
    type: markdown
    cascade: true
  icon:
    type: select
    options:
      allow_empty: true
      values:
        - ph-user-square
    cascade: true
  description:
    type: markdown
    options:
      allow_resize: true
      initial_height: 320
      bold: true
      image_size_attributes: true
      italic: true
      link: true
      removeformat: true
    cascade: true
  isActive:
    type: switch
    cascade: true
  social[*].icon:
    type: select
    options:
      allow_empty: true
      values:
        - ph-facebook-logo
        - ph-instagram-logo
        - ph-twitter-logo
        - ph-github-logo
        - ph-youtube-logo
    cascade: true
  page_description:
    type: text
    comment: If empty, defaults to the description set in the Site SEO data file
    cascade: true
  canonical_url:
    type: text
    comment: If empty, defaults to the URL of the page
    cascade: true
  featured_image:
    type: image
    comment: If empty, defaults to the image set in the Site SEO data file
    cascade: true
  author_twitter_handle:
    type: twitter
    comment: Defaults to the twitter site value set in the Site SEO data file
    cascade: true
  no_index:
    type: checkbox
    comment: >-
      When selected this removes the page from your sitemap and adds the noindex
      robots meta tag
    cascade: true
  open_graph_type:
    type: select
    options:
      allow_empty: true
      values:
        - website
        - article
        - profile
    cascade: true
  favicon_icon:
    type: image
    comment: For the shortcut icon meta tag
    cascade: true
  favicon_image:
    type: image
    comment: For the icon meta tag
    cascade: true
  enable_dropdown:
    type: switch
    cascade: true
  dropdown:
    type: array
    options:
      structures: _structures.dropdown
    label: Dropdown Items
    hidden: '!enable_dropdown'
    cascade: true
  dropdown_link:
    type: url
    label: Link
    cascade: true
  dropdown_text:
    type: text
    label: Name
    cascade: true
  items:
    type: array
    options:
      structures: _structures.items
    cascade: true
  logo:
    type: image
    cascade: true
  categories:
    type: multiselect
    options:
      empty_type: array
      values: data.blog-tags
    cascade: true
  twitter_site:
    type: twitter
    label: Twitter Username
    cascade: true
  logo_url:
    type: auto
    comment: Link for the logo in the top left of the footer
    cascade: true
  copyright:
    type: auto
    comment: Automatically prefixed with the current year
    cascade: true
  enable_nav_btn:
    type: switch
    cascade: true
  nav_btn:
    type: auto
    hidden: '!enable_nav_btn'
    cascade: true
_select_data: {}
_structures:
  content_blocks:
    style: modal
  dropdown:
    style: select
    values:
      value:
        dropdown_text:
        dropdown_link:
  social:
    style: select
    values:
      value:
        link:
        icon:
  sections:
    style: select
    values:
      value:
        title:
        links:
  links:
    style: select
    values:
      value:
        link:
        text:
  features:
    style: select
    values:
      - value:
          item:
          isActive:
  items:
    style: select
    values:
      value:
        link:
        text:
        enable_dropdown:
        dropdown:
_editables: {}
data_config:
  blog-tags: true
editor: {}
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Etc/UTC
_snippets_imports:
  hugo: true
