# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact
  description: Contact form, address, email, number and map iframe
  icon: location_on
  tags:
    - Form

# Defines the structure of this component, as well as the default values
blueprint:
  address: ""
  email: ""
  phone: ""
  map-iframe: ""
  layout: map_right

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  address: ""
  email: ""
  phone: ""
  map-iframe: ""

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  address:
    comment: Enter the contact address
  email:
    comment: Enter the contact Email address
  phone:
    comment: Enter the contact phone number
  map-iframe:
    comment: Enter the google iframe src
  layout:
    comment: Select the contact layout for the map.
    type: select
    options:
      values:
        - map_left
        - map_right
